title: Resources for Older Adults
description: Information for older adults
baseurl: "/olderadults/" # the subpath of your site, e.g. /blog
url: "https://info.waterlooregion.org" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

collections_dir: collections
collections:
  programs:
    output: true
    permalink: /programs/:path/

defaults:
  -
    scope:
      path: ""
      type: "programs"
    values:
      layout: "program"

remote_theme: pmarsceill/just-the-docs

