title: Resources for Older Adults
description: Information for older adults
baseurl: "/olderadults" # the subpath of your site, e.g. /blog
url: "https://info.waterlooregion.org" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: collections
collections:
  agencies:
    output: false
  programs:
    output: true
    permalink: /:collection/:path/ # https://jekyllrb.com/docs/permalinks/#collections
  topics:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "programs"
    values:
      layout: "program"

remote_theme: pmarsceill/just-the-docs

